# Copyright 2021, Matthew Winter
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---

- name: Create Ansible Google Cloud Service Account
  google.cloud.gcp_iam_service_account:
    name: "{{ item }}@{{ gcp_project_id }}.iam.gserviceaccount.com"
    display_name: "Ansible Service Account [{{ item }}]"
    project: "{{ gcp_project_id }}"
    auth_kind: application
    state: present
  with_items:
    - "{{ ansible_service_account }}"

- name: Grant Roles Required for the Ansible Google Cloud Service Account
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gcloud projects add-iam-policy-binding "{{ gcp_project_id }}" --member="serviceAccount:{{ ansible_service_account }}@{{ gcp_project_id }}.iam.gserviceaccount.com" --role="{{ item }}"
  args:
    executable: /bin/bash
  changed_when: false
  with_items:
    - "roles/compute.viewer"
    - "roles/iam.serviceAccountKeyAdmin"
    - "roles/secretmanager.admin"
    - "roles/gkehub.admin"

- name: Create Temp Directory
  ansible.builtin.tempfile:
    state: directory
    suffix: .keys
  register: tmpdir
  changed_when: false

- name: Create an Ansible Service Account Key and Add to Secret Manager
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      if ! $(gcloud secrets versions describe latest --secret="{{ item }}" >/dev/null 2>&1) ; then
        gcloud iam service-accounts keys create "{{ item }}.json" --iam-account "{{ item }}@{{ gcp_project_id }}.iam.gserviceaccount.com"
        if $(gcloud secrets describe "{{ item }}" >/dev/null 2>&1) ; then
          gcloud secrets versions add "{{ item }}" --data-file="{{ item }}.json"
        else
          gcloud secrets create "{{ item }}" --data-file="{{ item }}.json" --replication-policy=user-managed --locations="{{ secret_manager_locations }}"
        fi
        rm -f "{{ item }}.json"
      fi
    chdir: "{{ tmpdir.path }}"
  args:
    executable: /bin/bash
  changed_when: false
  with_items:
    - "{{ ansible_service_account }}"

- name: Cleanup Temp Directory
  ansible.builtin.file:
    path: "{{ tmpdir.path }}"
    state: absent
  changed_when: false
